version: 2.0
jobs:
  npm_audit_node_11: &npm_audit
    docker:
      - image: circleci/golang:1.12.0-node
    steps: 
      - checkout
      - run: 
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install hub
          command: |
              set -xe
              go get -u -d github.com/github/hub
              cd /go/src/github.com/github/hub
              go install github.com/github/hub
      - run:
          name: Submit PR if npm audit fix makes changes
          command: ./scripts/npm-audit-fix.sh

workflows:
  version: 2
  audit:
    jobs:
      - npm_audit_node_11

  nightly:
     triggers:
       - schedule:
           cron: "50 23 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - npm_audit_node_11
